# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-08 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decisiontree', '0004_answer_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='The text to send to the user, e.g., a question, completion text.', max_length=500, verbose_name='message text')),
                ('error_response', models.CharField(blank=True, help_text='Optional error message if the user does not send a valid response.', max_length=160)),
            ],
        ),
        migrations.RemoveField(
            model_name='tree',
            name='completion_text',
        ),
        migrations.RemoveField(
            model_name='treestate',
            name='question',
        ),
        migrations.AlterField(
            model_name='answer',
            name='type',
            field=models.CharField(choices=[('A', 'Exact Match'), ('R', 'Regular Expression'), ('C', 'Custom Logic')], max_length=1),
        ),
        migrations.AlterField(
            model_name='session',
            name='num_tries',
            field=models.PositiveIntegerField(help_text='The number of times the user has tried to respond to the current message.'),
        ),
        migrations.AlterField(
            model_name='session',
            name='state',
            field=models.ForeignKey(blank=True, help_text='None if the session is complete.', null=True, on_delete=django.db.models.deletion.CASCADE, to='decisiontree.TreeState'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='next_state',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='next_state', to='decisiontree.TreeState'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tree',
            name='root_state',
            field=models.ForeignKey(help_text='The first Message sent when this Tree is triggered, which may lead to many more.', on_delete=django.db.models.deletion.CASCADE, related_name='tree_set', to='decisiontree.TreeState'),
        ),
        migrations.AlterField(
            model_name='tree',
            name='trigger',
            field=models.CharField(help_text='The incoming message which triggers this Tree.', max_length=30, unique=True, verbose_name='Keyword'),
        ),
        migrations.AlterField(
            model_name='treestate',
            name='num_retries',
            field=models.PositiveIntegerField(blank=True, help_text="The number of tries the user has to get out of this state. If empty, there is no limit. When the number of retries is hit, the user's session will be terminated.", null=True),
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='treestate',
            name='message',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='decisiontree.Message'),
            preserve_default=False,
        ),
    ]
