# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-24 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decisiontree', '0005_auto_20180808_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='state_at_close',
            field=models.ForeignKey(blank=True, help_text='State when the session closes.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_at_close', to='decisiontree.TreeState'),
        ),
    ]
