# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-29 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisiontree', '0006_session_state_at_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recommendation',
            field=models.BooleanField(default=False),
        ),
    ]
