# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-04 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisiontree', '0007_message_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(help_text='The text to send to the user, e.g., a question, completion text.', max_length=500, verbose_name='message text'),
        ),
    ]
