# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-25 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decisiontree', '0009_auto_20181228_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(help_text='The text to send to the user, e.g., a question, completion text.', max_length=1000, verbose_name='message text'),
        ),
    ]
